model_name_or_path: /users/ddixit/scratch/apertus-project/huggingface_cache/models--swiss-ai--Apertus-8B-Instruct-2509/snapshots/cdb3e4f4ad41e0cc394bb92c302ac2eed57e9586
attn_implementation: flash_attention_2
dtype: bfloat16
dataset_name: /users/ddixit/scratch/apertus-project/apertus-finetuning-recipes/json_datasets/my_train.jsonl
dataset_num_proc: 12
learning_rate: 1.0e-05
gradient_checkpointing: true
num_train_epochs: 3.0
logging_steps: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
max_grad_norm: 1.0
eval_strategy: steps
eval_steps: 15
per_device_eval_batch_size: 1
save_strategy: steps
save_steps: 15
save_total_limit: 5
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
use_peft: true
lora_r: 32
lora_alpha: 64
lora_dropout: 0.1
lora_target_modules: all-linear
max_length: 4096
warmup_ratio: 0.1
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
output_dir: /users/ddixit/scratch/apertus-project/output_22
report_to: none
seed: 42
