# Model
model_name_or_path: swiss-ai/Apertus-8B-Instruct-2509
attn_implementation:  kernels-community/vllm-flash-attn3
dtype: bfloat16

# Dataset
dataset_name: medalpaca/medical_meadow_medical_flashcards
dataset_config: null  # This dataset has no subsets/configs
dataset_train_split: train  # The split name to use for training
dataset_test_split: train  # Use train split since there's no test split
dataset_num_proc: 12

# Hyperparameters
learning_rate: 2.0e-4
gradient_checkpointing: true
num_train_epochs: 1.0
logging_steps: 1
per_device_train_batch_size: 4
gradient_accumulation_steps: 1

# LoRA / PEFT
use_peft: true
lora_r: 8
lora_alpha: 16
lora_dropout: 0.0
lora_target_modules: all-linear

# Seq length & scheduler
max_length: 4096
warmup_ratio: 0.03
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1

# Output & logging
output_dir: /users/$USER/scratch/apertus/output/apertus_lora
report_to: "none" 
seed: 42
